/**
 * Benchmark seeder — builds a `.slop/db` of arbitrary size FAST.
 *
 * Why this bypasses the CLI: seeding a six-figure ticket count by spawning
 * `slop new` that many times would take hours and would measure process
 * startup, not the datastore. This writes entity files directly through the
 * same primitives the repo layer uses (`writeCanonical` + a plain write),
 * then lets the real `loadIndex`/`buildIndex` path do all the reading during
 * the actual measurements. Every ticket it emits is schema-valid —
 * `--verify` asserts that by running the real `ticketSchema` over a sample,
 * so a seeding bug can never quietly become a "look how fast it is" result.
 * Events land in their real `events/<YYYY-MM>/` shard (G2), never flat, so
 * the index/fingerprint scans measured here exercise the same
 * shard-directory enumeration a real repo's `buildIndex` does.
 *
 * Deliberately NOT atomic-write: `atomicWriteFile` costs a temp file + fsync +
 * directory fsync per entity, which is the right thing for a real mutation and
 * pure overhead for building a fixture. Seeding is not what's being measured.
 *
 * G5 (t-ukxun): this harness previously also swept a 1,000,000-ticket rung.
 * That column is gone — see docs/benchmarks.md's methodology note for why —
 * but nothing about this seeder's own bypass-the-CLI, bypass-atomic-write
 * rationale was scale-specific, so both still apply verbatim at the rungs
 * this now actually runs (1k/10k/100k).
 */
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { newEventId, newTicketId, ticketSchema, writeCanonical } from "../src/core/index.js";
import type { EventId, Ticket, TicketId } from "../src/core/index.js";
import { eventShardMonth } from "../src/repo/index.js";

export interface SeedOptions {
  /** Directory that will contain `.slop/` (not `.slop/` itself). */
  root: string;
  tickets: number;
  /** Extra `ticket.updated` events, spread across the seeded tickets. */
  events?: number;
  /** How many tickets the FIRST seeded ticket blocks — the wide-cascade fixture. */
  blocksFanout?: number;
  /** Files written per batch; bounds open file descriptors. */
  batchSize?: number;
}

export interface SeedResult {
  root: string;
  tickets: number;
  events: number;
  /** The blocker in the fan-out fixture, if one was built. */
  cascadeBlocker: TicketId | null;
  /** A ticket from the middle of the set — a fair ref-resolution target. */
  sampleId: TicketId;
  sampleSlug: string;
  seedMs: number;
}

const ISO = "2026-01-01T00:00:00.000Z";

function buildTicket(index: number, id: TicketId, blocks: TicketId[] = []): Ticket {
  return {
    id,
    name: `Bench ticket ${index}`,
    slug: `bench-ticket-${index}`,
    spec: {
      summary: `Bench ticket ${index}`,
      details_md:
        `Synthetic ticket #${index} generated by bench/seed.ts. Body text exists so ` +
        "specs are not unrealistically small: real tickets carry prose, and `search` " +
        "has to scan it.",
      acceptance: [`bench criterion ${index}`],
      context: ["bench/seed.ts"],
      meta: {},
      v: 1,
    },
    state: "open",
    priority: (index % 4) as 0 | 1 | 2 | 3,
    labels: index % 5 === 0 ? ["area:bench"] : [],
    blocks,
    relates_to: [],
    discovered_from: [],
    root_id: id,
    path: [],
    active_session: null,
    last_activity_at: ISO,
    latest_note: null,
    owner: null,
    provenance: { method: "new", created_by: { name: "bench", kind: "human" } },
    created_at: ISO,
    updated_at: ISO,
  } as Ticket;
}

function buildEvent(ticketId: TicketId, n: number): Record<string, unknown> {
  return {
    id: newEventId(),
    actor: { name: "bench", kind: "human" },
    session: null,
    verb: "ticket.updated",
    entity: { kind: "ticket", id: ticketId },
    payload: { progress: `bench progress note ${n}` },
    at: ISO,
  };
}

/** Write `items` in bounded-concurrency batches so a six-figure seed doesn't
 * try to hold every promise (or file descriptor) open at once. */
async function writeBatched<T>(
  items: readonly T[],
  batchSize: number,
  write: (item: T) => Promise<void>,
): Promise<void> {
  for (let i = 0; i < items.length; i += batchSize) {
    await Promise.all(items.slice(i, i + batchSize).map(write));
  }
}

export async function seed(options: SeedOptions): Promise<SeedResult> {
  const { root, tickets: ticketCount } = options;
  const eventCount = options.events ?? 0;
  const fanout = options.blocksFanout ?? 0;
  const batchSize = options.batchSize ?? 512;

  const ticketsDir = join(root, ".slop", "db", "tickets");
  const eventsDir = join(root, ".slop", "db", "events");
  await mkdir(ticketsDir, { recursive: true });
  await mkdir(eventsDir, { recursive: true });
  await mkdir(join(root, ".slop", "db", "sessions"), { recursive: true });

  const started = performance.now();

  // Mint every id up front: the fan-out fixture needs ticket 0 to name ids that
  // don't exist yet, and ULIDs are monotonic so creation order is preserved.
  const ids: TicketId[] = Array.from({ length: ticketCount }, () => newTicketId());

  const blocked = fanout > 0 ? ids.slice(1, Math.min(1 + fanout, ids.length)) : [];

  await writeBatched(
    ids.map((id, i) => ({ id, i })),
    batchSize,
    async ({ id, i }) => {
      const ticket = buildTicket(i, id, i === 0 ? blocked : []);
      await writeFile(join(ticketsDir, `${id}.jsonc`), writeCanonical(ticket), "utf8");
    },
  );

  if (eventCount > 0) {
    const eventIndexes = Array.from({ length: eventCount }, (_, n) => n);
    // G5 (t-ukxun): seed through the CURRENT (G2, shard-event-storage)
    // physical layout — `events/<YYYY-MM>/event_<ulid>.jsonc` — never
    // flat, so the index/fingerprint scans this harness measures exercise
    // the same shard-directory enumeration a real repo's `buildIndex`
    // does (see `src/repo/events.ts`'s module doc). `shardDirsMkdirred`
    // caches which shard directories already exist so a seed of hundreds
    // of thousands of events (all minted "now," so they land in the same
    // one or two month shards) doesn't `mkdir` the same directory once
    // per file.
    const shardDirsMkdirred = new Set<string>();
    await writeBatched(eventIndexes, batchSize, async (n) => {
      const target = ids[n % ids.length];
      if (target === undefined) return;
      const event = buildEvent(target, n);
      const id = event.id as EventId;
      const shardDir = join(eventsDir, eventShardMonth(id));
      if (!shardDirsMkdirred.has(shardDir)) {
        await mkdir(shardDir, { recursive: true });
        shardDirsMkdirred.add(shardDir);
      }
      await writeFile(join(shardDir, `${id}.jsonc`), writeCanonical(event), "utf8");
    });
  }

  const seedMs = performance.now() - started;
  const middle = Math.floor(ticketCount / 2);
  const sampleId = ids[middle] ?? ids[0];
  if (sampleId === undefined) throw new Error("seed: refusing to seed zero tickets");

  return {
    root,
    tickets: ticketCount,
    events: eventCount,
    cascadeBlocker: fanout > 0 ? (ids[0] ?? null) : null,
    sampleId,
    sampleSlug: `bench-ticket-${middle}`,
    seedMs,
  };
}

/** Prove the seeder emits real, schema-valid tickets — see the module doc. */
export async function verifySample(root: string, sampleId: TicketId): Promise<void> {
  const { readFile } = await import("node:fs/promises");
  const { parseJsonc } = await import("../src/core/index.js");
  const raw = await readFile(join(root, ".slop", "db", "tickets", `${sampleId}.jsonc`), "utf8");
  const { value, errors } = parseJsonc<unknown>(raw);
  if (errors.length > 0) throw new Error(`seed produced unparseable JSONC for ${sampleId}`);
  const parsed = ticketSchema.safeParse(value);
  if (!parsed.success) {
    throw new Error(
      `seed produced a schema-INVALID ticket (${sampleId}): ${JSON.stringify(parsed.error.issues.slice(0, 3))}`,
    );
  }
}
