#!/usr/bin/env bun
/**
 * Builds the `slop web` React SPA into two static, self-contained text
 * assets (`src/web/generated/app.js`, `src/web/generated/app.css`) that
 * `src/web/server.ts` then embeds into the compiled binary via Bun's
 * `with { type: "text" }` import attribute — the exact same mechanism the
 * old hand-written `src/web/assets/{app.js,style.css}` used, just with a
 * real bundle on the left-hand side now.
 *
 * Two things happen here that a plain `bun build` CLI invocation can't do
 * in one step:
 *
 *  1. Font inlining (rewrite-slop-web-as-a's "self-host/bundle" requirement,
 *     constraint 1): a JetBrains Mono subset (latin, 400 + 600, woff2 only —
 *     `@fontsource/jetbrains-mono` ships every weight/script combination
 *     unsubsetted) is base64-inlined into `src/web/frontend/fonts.generated.css`
 *     — a small, git-ignored, deterministically-regenerated file the main
 *     stylesheet `@import`s — so the font ships as text inside the same
 *     bundle, never a separate request, and Tailwind's own bundler never
 *     has to understand binary asset loaders at all.
 *  2. Tailwind v4 (`bun-plugin-tailwind`, the framework's own Bun plugin —
 *     no PostCSS/CLI step needed) runs as a `Bun.build` plugin so the whole
 *     SPA — JS and CSS — comes out of one `Bun.build()` call.
 *
 * Run via `bun run build:web` (also a `pretest`/`prebuild` dependency — see
 * package.json — so both `bun run test` and `bun run build` always work
 * against freshly generated assets, never stale ones).
 */
import { watch } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import tailwindPlugin from "bun-plugin-tailwind";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const frontendDir = join(repoRoot, "src", "web", "frontend");
const outDir = join(repoRoot, "src", "web", "generated");

const FONT_WEIGHTS: Array<{ weight: number; cssWeight: string }> = [
  { weight: 400, cssWeight: "400" },
  { weight: 600, cssWeight: "600" },
];

/** Base64-inline the bundled JetBrains Mono (latin subset only) woff2 files
 * into a generated CSS partial — see this module's doc for why. */
async function generateFontsCss(): Promise<void> {
  const fontPkgDir = join(repoRoot, "node_modules", "@fontsource", "jetbrains-mono", "files");
  const blocks = await Promise.all(
    FONT_WEIGHTS.map(async ({ weight, cssWeight }) => {
      const path = join(fontPkgDir, `jetbrains-mono-latin-${weight}-normal.woff2`);
      const bytes = await readFile(path);
      const base64 = bytes.toString("base64");
      return `@font-face {
  font-family: "JetBrains Mono";
  font-style: normal;
  font-weight: ${cssWeight};
  font-display: swap;
  src: url(data:font/woff2;base64,${base64}) format("woff2");
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
}`;
    }),
  );
  const banner =
    "/* GENERATED by scripts/build-frontend.ts — do not edit by hand.\n" +
    "   JetBrains Mono (OFL-1.1), latin subset, weights 400/600, woff2-only,\n" +
    "   base64-inlined so the font ships inside the CSS text with zero extra\n" +
    "   network requests at runtime. */\n\n";
  await writeFile(join(frontendDir, "fonts.generated.css"), banner + blocks.join("\n\n") + "\n");
}

async function buildBundle(): Promise<void> {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const result = await Bun.build({
    entrypoints: [join(frontendDir, "main.tsx")],
    outdir: outDir,
    target: "browser",
    format: "esm",
    minify: true,
    sourcemap: "none",
    naming: { entry: "app.[ext]", asset: "[name]-[hash].[ext]" },
    define: {
      "process.env.NODE_ENV": JSON.stringify("production"),
    },
    plugins: [tailwindPlugin],
  });

  if (!result.success) {
    for (const message of result.logs) {
      console.error(message);
    }
    throw new Error("frontend build failed — see logs above");
  }

  const produced = (await readdir(outDir)).sort();
  console.log(`slop web frontend built -> ${outDir} (${produced.join(", ")})`);

  const hasJs = produced.some((name) => name === "app.js");
  const hasCss = produced.some((name) => name === "app.css");
  if (!hasJs || !hasCss) {
    throw new Error(
      `expected src/web/generated/app.js AND app.css, got: ${produced.join(", ") || "(nothing)"}`,
    );
  }
}

async function build(): Promise<void> {
  await generateFontsCss();
  await buildBundle();
}

await build();

/** `bun run dev:web` — rebuild on every source change (fonts.generated.css
 * excluded, since it's this script's own output, to avoid a rebuild loop).
 * No incremental compilation here: a full `Bun.build()` re-run is well
 * under a second for a SPA this size, which is fast enough for a local dev
 * loop without the complexity of a persistent bundler/HMR server — see
 * README's "Web UI development" section. */
if (process.argv.includes("--watch")) {
  console.log("watching src/web/frontend for changes (Ctrl-C to stop)...");
  let pending = false;
  let rebuilding = false;
  const scheduleRebuild = () => {
    if (rebuilding) {
      pending = true;
      return;
    }
    rebuilding = true;
    build()
      .catch((err: unknown) => console.error(err))
      .finally(() => {
        rebuilding = false;
        if (pending) {
          pending = false;
          scheduleRebuild();
        }
      });
  };
  watch(frontendDir, { recursive: true }, (_event, filename) => {
    if (filename?.endsWith("fonts.generated.css")) return;
    scheduleRebuild();
  });
}
