/**
 * {@link FixtureDataSource}: a {@link WebDataSource} that reads a
 * `.slop`-shaped directory straight off disk (design.md §3's layout —
 * `config.yaml`, `db/tickets/*.jsonc`, `db/sessions/*.jsonc`,
 * `db/events/*.jsonc`, `transcripts/*.jsonl`) with plain filesystem calls,
 * validating every file against the A2 zod schemas so a malformed fixture
 * fails loudly instead of silently drifting from the real shapes.
 *
 * This work item points it at the committed fixture db
 * (tests/fixtures/web-db/.slop/, generated by
 * tests/fixtures/generate-web-db.ts) — hence the name — but nothing about
 * the implementation is fixture-specific: it works against *any* directory
 * in this shape, including a real project's `.slop/`. `src/cli/commands/web.ts`
 * therefore also uses this class today, pointed at the `.slop` directory
 * discovered by walking up from the current working directory, which is
 * what makes `slop web` actually usable before the real repo layer lands
 * (see this file's final doc comment for exactly what a later work item
 * should still change).
 *
 * Deliberately NOT reused from src/repo/ (that lane is being built
 * concurrently by another work item and this one must not depend on it):
 * there is no locking, no atomic writes (this class never writes), no
 * persisted `index.jsonc` — `blocked`/`stale` and the reverse blocks-edge
 * index are recomputed in memory on every call (src/web/overlays.ts). That
 * is a real behavioural difference from a future repo-layer-backed
 * adapter (which could reuse B4's persisted index for O(1) lookups at
 * scale instead of O(n) in-memory scans) — acceptable at v0's target
 * scale (a handful of agents, hundreds not millions of tickets), and
 * called out explicitly in this work item's report.
 */
import { readdir } from "node:fs/promises";
import { basename, isAbsolute, join, relative, resolve } from "node:path";
import {
  configSchema,
  type Event,
  eventSchema,
  idMatchesRef,
  isSessionId,
  parseJsonc,
  type Session,
  type SessionId,
  sessionSchema,
  type Ticket,
  type TicketId,
  ticketSchema,
} from "../core/index.js";
import type { ConfigResult, TranscriptHandle, WebDataSource } from "./data-source.js";

/**
 * web-one-malformed-db-file-500s-every-page-and-leaks-filesyst: this used
 * to read+parse every file in `dir` strictly (`for` loop, first throw wins)
 * — which meant one corrupt/schema-drifted `.jsonc` file took the ENTIRE
 * listing down with it, and every view built on that listing along with it
 * (`/tickets`, `/tree`, `/review`, `/stale`, and — via `findTicketByRef`
 * re-`listTickets()`-ing — even an unrelated ticket's own detail page).
 *
 * Mirrors the fault-tolerant `Promise.allSettled` pattern
 * `repo/tickets.ts`'s `listTicketsTolerant` (reused by `repo/db-index.ts`'s
 * `buildIndex`, see that module's "Fault tolerance" doc section) already
 * established for exactly this class of problem: a file that fails to
 * read, parse as JSONC, or validate against its schema is skipped and
 * logged (stderr, via {@link warnSkippedFiles}) rather than aborting the
 * whole directory read. Every other file in `dir` is still returned,
 * unaffected — so one bad ticket/session/event file degrades to "N fewer
 * rows in the listing", never a 500 on every page that listing feeds.
 *
 * Direct single-entity reads (`getSessionById`, `getConfig`) are
 * deliberately UNCHANGED and still throw on a corrupt file — same
 * reasoning `repo/tickets.ts`'s `readTicket`/`listTickets` doc gives: a
 * direct-by-id read is the caller asking for that exact entity and has no
 * sensible "skip it" option. This function is only ever used for
 * *listings* (`listTickets`, the sessions/events dirs) — see this module's
 * callers.
 */
async function readJsoncDir<T>(
  dir: string,
  parseOne: (text: string, file: string) => T,
): Promise<T[]> {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch (err) {
    if (err instanceof Error && "code" in err && err.code === "ENOENT") return [];
    throw err;
  }
  const files = entries.filter((name) => name.endsWith(".jsonc")).sort();
  const settled = await Promise.allSettled(
    files.map(async (file) => {
      const path = join(dir, file);
      const text = await Bun.file(path).text();
      return parseOne(text, path);
    }),
  );

  const out: T[] = [];
  const skipped: string[] = [];
  for (const result of settled) {
    if (result.status === "fulfilled") {
      out.push(result.value);
    } else {
      const message =
        result.reason instanceof Error ? result.reason.message : String(result.reason);
      skipped.push(message);
    }
  }
  if (skipped.length > 0) warnSkippedFiles(dir, skipped);
  return out;
}

/**
 * Never-silent counterpart to the skip-and-continue behaviour above —
 * matches `repo/db-index.ts`'s `warnAboutIndexProblems`: a skipped file is
 * degraded service, not something that should vanish without a trace.
 * stderr only (this is a read-only local dev server; there is no request
 * -scoped logger to route through), one line per directory read that hit
 * at least one bad file, each skipped file's own high-quality parse/schema
 * error indented beneath it.
 */
function warnSkippedFiles(dir: string, messages: string[]): void {
  const header = `slop web: ${messages.length} file(s) in ${dir} failed to load and were skipped:`;
  const body = messages.map((message) => `  - ${message}`).join("\n");
  process.stderr.write(`${header}\n${body}\n`);
}

function parseEntity<T>(schema: { parse: (input: unknown) => T }, text: string, path: string): T {
  const { value, errors } = parseJsonc<unknown>(text);
  if (errors.length > 0) {
    throw new Error(`${path}: invalid JSONC (${errors.length} parse error(s))`);
  }
  try {
    return schema.parse(value);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`${path}: failed schema validation — ${message}`);
  }
}

/**
 * True iff resolved absolute path `candidate` is `root` itself or lives
 * strictly inside it — i.e. `path.relative(root, candidate)` doesn't
 * escape upward (`..`) and isn't itself an absolute path (which
 * `path.relative` returns when `candidate` is on an unrelated path, e.g.
 * a different drive on Windows).
 *
 * The one and only guard against a `transcript_ref` path-traversal
 * (`../../etc/passwd` and friends) reading arbitrary files off the host —
 * see this module's final doc comment and `openTranscript` below, which
 * is the sole caller. `.slop/db` is a git-mergeable, collaborator-editable
 * store, so a tampered or buggy `transcript_ref` is a realistic input,
 * not just a theoretical one. Exported for direct unit testing of the
 * predicate itself, independent of the filesystem.
 */
export function isContainedPath(root: string, candidate: string): boolean {
  if (candidate === root) return true;
  const rel = relative(root, candidate);
  // path.relative() returns a string starting with ".." when `candidate`
  // is outside `root`, and an absolute path when the two share no common
  // root at all (e.g. different drives on Windows) — both mean "escaped".
  return rel !== "" && !rel.startsWith("..") && !isAbsolute(rel);
}

/** Streaming line reader over a file on disk — see src/web/transcript.ts's module doc for why this matters for large transcripts. */
async function* readLines(path: string): AsyncGenerator<string> {
  const stream = Bun.file(path).stream();
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let newlineIndex = buffer.indexOf("\n");
      while (newlineIndex >= 0) {
        yield buffer.slice(0, newlineIndex);
        buffer = buffer.slice(newlineIndex + 1);
        newlineIndex = buffer.indexOf("\n");
      }
    }
    if (buffer.length > 0) yield buffer;
  } finally {
    reader.releaseLock();
    await stream.cancel().catch(() => {});
  }
}

/**
 * `project` has no schema default (design.md §3: it's required, prompted at
 * `init`) — so a synthesized fallback {@link Config} needs an explicit
 * stand-in. Deliberately visible/unusual rather than something that could
 * pass for a real project name, since {@link FixtureDataSource.getConfig}
 * only ever returns this alongside a non-null `warning` the caller is
 * expected to surface too.
 */
const FALLBACK_PROJECT_LABEL = "(unknown — config.yaml unavailable)";

export class FixtureDataSource implements WebDataSource {
  /** Root of a `.slop` directory (design.md §3) — the directory that directly contains `config.yaml`, `db/`, and `transcripts/`. */
  constructor(private readonly slopRoot: string) {}

  /**
   * web-corrupt-or-missing-config: never throws. `config.yaml` missing
   * (ENOENT), unreadable, invalid YAML, or schema-invalid all degrade to
   * the same outcome — a synthesized default {@link Config} plus a non-null
   * `warning` — instead of taking every §4.4 view down with a 500 (they all
   * call this). Logged to stderr too (matches {@link warnSkippedFiles}'s
   * convention for the tickets/sessions/events listings) so a real `slop
   * web` operator sees it even if they don't have the browser open.
   */
  async getConfig(): Promise<ConfigResult> {
    const path = join(this.slopRoot, "config.yaml");
    try {
      const text = await Bun.file(path).text();
      const parsed: unknown = Bun.YAML.parse(text);
      return { config: configSchema.parse(parsed), warning: null };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      const warning = `config.yaml could not be read — showing defaults (${message})`;
      process.stderr.write(`slop web: ${path}: ${message}\n`);
      return { config: configSchema.parse({ project: FALLBACK_PROJECT_LABEL }), warning };
    }
  }

  async listTickets(): Promise<Ticket[]> {
    return readJsoncDir(join(this.slopRoot, "db", "tickets"), (text, path) =>
      parseEntity(ticketSchema, text, path),
    );
  }

  async findTicketByRef(ref: string): Promise<Ticket | null> {
    const tickets = await this.listTickets();
    const bySlug = tickets.find((t) => t.slug === ref);
    if (bySlug) return bySlug;
    const byId = tickets.find((t) => t.id === ref);
    if (byId) return byId;
    // Unambiguous short id-prefix (D6/D12) — same matching rule the CLI's ref
    // resolution uses (core/ids.ts idMatchesRef), reused rather than reimplemented.
    const prefixMatches = tickets.filter((t) => idMatchesRef(t.id, ref));
    return prefixMatches.length === 1 ? (prefixMatches[0] ?? null) : null;
  }

  async listSessionsForTicket(ticketId: TicketId): Promise<Session[]> {
    const all = await readJsoncDir(join(this.slopRoot, "db", "sessions"), (text, path) =>
      parseEntity(sessionSchema, text, path),
    );
    return all
      .filter((s) => s.ticket === ticketId)
      .sort((a, b) => a.started_at.localeCompare(b.started_at));
  }

  async getSessionById(id: SessionId): Promise<Session | null> {
    if (!isSessionId(id)) return null;
    const path = join(this.slopRoot, "db", "sessions", `${id}.jsonc`);
    const file = Bun.file(path);
    if (!(await file.exists())) return null;
    return parseEntity(sessionSchema, await file.text(), path);
  }

  /** The full `db/events/` directory, fault-tolerantly read — shared by
   * {@link listEventsForTicket} and {@link listEvents} so the two never
   * drift on what counts as a readable event file. */
  private readAllEvents(): Promise<Event[]> {
    return readJsoncDir(join(this.slopRoot, "db", "events"), (text, path) =>
      parseEntity(eventSchema, text, path),
    );
  }

  async listEventsForTicket(ticketId: TicketId): Promise<Event[]> {
    const [events, sessions] = await Promise.all([
      this.readAllEvents(),
      this.listSessionsForTicket(ticketId),
    ]);
    const sessionIds = new Set<string>(sessions.map((s) => s.id));
    const relevant = events.filter(
      (e) =>
        (e.entity.kind === "ticket" && e.entity.id === ticketId) ||
        (e.entity.kind === "session" && sessionIds.has(e.entity.id)),
    );
    // Event ids are ULIDs (D6): lexicographic order is chronological order.
    return relevant.sort((a, b) => a.id.localeCompare(b.id));
  }

  async listEvents(): Promise<Event[]> {
    return this.readAllEvents();
  }

  async openTranscript(transcriptRef: string): Promise<TranscriptHandle | null> {
    // Convention this work item defines (see D5 report): transcript_ref is
    // a path relative to the `.slop` root, e.g. "transcripts/session_….jsonl".
    //
    // transcript_ref comes from a session file in `.slop/db` — a
    // git-mergeable, collaborator-editable store — so it cannot be
    // trusted to actually be that shape. sessionSchema (src/core/entities
    // /session.ts) rejects the obvious bad forms up front, but this is the
    // load-bearing check: resolve the joined path and confirm it's still
    // inside the resolved `.slop` root before ever touching the
    // filesystem. A ref that escapes (`../`, an absolute path that slips
    // past the schema, a symlink-free `..` segment buried mid-path, etc.)
    // is treated exactly like "file not found" — never opened.
    const root = resolve(this.slopRoot);
    const path = resolve(join(this.slopRoot, transcriptRef));
    if (!isContainedPath(root, path)) return null;
    const file = Bun.file(path);
    if (!(await file.exists())) return null;
    return {
      ref: basename(path),
      lines: () => readLines(path),
    };
  }
}
