/**
 * {@link FixtureDataSource}: a {@link WebDataSource} that reads a
 * `.slop`-shaped directory straight off disk (design.md §3's layout —
 * `config.yaml`, `db/tickets/*.jsonc`, `db/sessions/*.jsonc`,
 * `db/events/*.jsonc`, `transcripts/*.jsonl`) with plain filesystem calls,
 * validating every file against the A2 zod schemas so a malformed fixture
 * fails loudly instead of silently drifting from the real shapes.
 *
 * This work item points it at the committed fixture db
 * (tests/fixtures/web-db/.slop/, generated by
 * tests/fixtures/generate-web-db.ts) — hence the name — but nothing about
 * the implementation is fixture-specific: it works against *any* directory
 * in this shape, including a real project's `.slop/`. `src/cli/commands/web.ts`
 * therefore also uses this class today, pointed at the `.slop` directory
 * discovered by walking up from the current working directory, which is
 * what makes `slop web` actually usable before the real repo layer lands
 * (see this file's final doc comment for exactly what a later work item
 * should still change).
 *
 * Deliberately NOT reused from src/repo/ (that lane is being built
 * concurrently by another work item and this one must not depend on it):
 * there is no locking, no atomic writes (this class never writes), no
 * persisted `index.jsonc` — `blocked`/`stale` and the reverse blocks-edge
 * index are recomputed in memory on every call (src/web/overlays.ts). That
 * is a real behavioural difference from a future repo-layer-backed
 * adapter (which could reuse B4's persisted index for O(1) lookups at
 * scale instead of O(n) in-memory scans) — acceptable at v0's target
 * scale (a handful of agents, hundreds not millions of tickets), and
 * called out explicitly in this work item's report.
 */
import { readdir } from "node:fs/promises";
import { basename, join } from "node:path";
import {
  type Config,
  type Event,
  type Session,
  type SessionId,
  type Ticket,
  type TicketId,
  configSchema,
  eventSchema,
  idMatchesRef,
  isSessionId,
  parseJsonc,
  sessionSchema,
  ticketSchema,
} from "../core/index.js";
import type { TranscriptHandle, WebDataSource } from "./data-source.js";

async function readJsoncDir<T>(
  dir: string,
  parseOne: (text: string, file: string) => T,
): Promise<T[]> {
  let entries: string[];
  try {
    entries = await readdir(dir);
  } catch (err) {
    if (err instanceof Error && "code" in err && err.code === "ENOENT") return [];
    throw err;
  }
  const files = entries.filter((name) => name.endsWith(".jsonc")).sort();
  const out: T[] = [];
  for (const file of files) {
    const path = join(dir, file);
    const text = await Bun.file(path).text();
    out.push(parseOne(text, path));
  }
  return out;
}

function parseEntity<T>(schema: { parse: (input: unknown) => T }, text: string, path: string): T {
  const { value, errors } = parseJsonc<unknown>(text);
  if (errors.length > 0) {
    throw new Error(`${path}: invalid JSONC (${errors.length} parse error(s))`);
  }
  try {
    return schema.parse(value);
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`${path}: failed schema validation — ${message}`);
  }
}

/** Streaming line reader over a file on disk — see src/web/transcript.ts's module doc for why this matters for large transcripts. */
async function* readLines(path: string): AsyncGenerator<string> {
  const stream = Bun.file(path).stream();
  const reader = stream.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      buffer += decoder.decode(value, { stream: true });
      let newlineIndex = buffer.indexOf("\n");
      while (newlineIndex >= 0) {
        yield buffer.slice(0, newlineIndex);
        buffer = buffer.slice(newlineIndex + 1);
        newlineIndex = buffer.indexOf("\n");
      }
    }
    if (buffer.length > 0) yield buffer;
  } finally {
    reader.releaseLock();
    await stream.cancel().catch(() => {});
  }
}

export class FixtureDataSource implements WebDataSource {
  /** Root of a `.slop` directory (design.md §3) — the directory that directly contains `config.yaml`, `db/`, and `transcripts/`. */
  constructor(private readonly slopRoot: string) {}

  async getConfig(): Promise<Config> {
    const path = join(this.slopRoot, "config.yaml");
    const text = await Bun.file(path).text();
    const parsed: unknown = Bun.YAML.parse(text);
    try {
      return configSchema.parse(parsed);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      throw new Error(`${path}: failed schema validation — ${message}`);
    }
  }

  async listTickets(): Promise<Ticket[]> {
    return readJsoncDir(join(this.slopRoot, "db", "tickets"), (text, path) =>
      parseEntity(ticketSchema, text, path),
    );
  }

  async findTicketByRef(ref: string): Promise<Ticket | null> {
    const tickets = await this.listTickets();
    const bySlug = tickets.find((t) => t.slug === ref);
    if (bySlug) return bySlug;
    const byId = tickets.find((t) => t.id === ref);
    if (byId) return byId;
    // Unambiguous short id-prefix (D6/D12) — same matching rule the CLI's ref
    // resolution uses (core/ids.ts idMatchesRef), reused rather than reimplemented.
    const prefixMatches = tickets.filter((t) => idMatchesRef(t.id, ref));
    return prefixMatches.length === 1 ? (prefixMatches[0] ?? null) : null;
  }

  async listSessionsForTicket(ticketId: TicketId): Promise<Session[]> {
    const all = await readJsoncDir(join(this.slopRoot, "db", "sessions"), (text, path) =>
      parseEntity(sessionSchema, text, path),
    );
    return all
      .filter((s) => s.ticket === ticketId)
      .sort((a, b) => a.started_at.localeCompare(b.started_at));
  }

  async getSessionById(id: SessionId): Promise<Session | null> {
    if (!isSessionId(id)) return null;
    const path = join(this.slopRoot, "db", "sessions", `${id}.jsonc`);
    const file = Bun.file(path);
    if (!(await file.exists())) return null;
    return parseEntity(sessionSchema, await file.text(), path);
  }

  async listEventsForTicket(ticketId: TicketId): Promise<Event[]> {
    const [events, sessions] = await Promise.all([
      readJsoncDir(join(this.slopRoot, "db", "events"), (text, path) =>
        parseEntity(eventSchema, text, path),
      ),
      this.listSessionsForTicket(ticketId),
    ]);
    const sessionIds = new Set<string>(sessions.map((s) => s.id));
    const relevant = events.filter(
      (e) =>
        (e.entity.kind === "ticket" && e.entity.id === ticketId) ||
        (e.entity.kind === "session" && sessionIds.has(e.entity.id)),
    );
    // Event ids are ULIDs (D6): lexicographic order is chronological order.
    return relevant.sort((a, b) => a.id.localeCompare(b.id));
  }

  async openTranscript(transcriptRef: string): Promise<TranscriptHandle | null> {
    // Convention this work item defines (see D5 report): transcript_ref is
    // a path relative to the `.slop` root, e.g. "transcripts/session_….jsonl".
    const path = join(this.slopRoot, transcriptRef);
    const file = Bun.file(path);
    if (!(await file.exists())) return null;
    return {
      ref: basename(path),
      lines: () => readLines(path),
    };
  }
}
